### ISSUE TITLE
sra_attributes : sra.run_alias explanation 

### ISSUE THREAD

**Issue by PinaColadast** [LieberInstitute/recount3#10]
Hi Recount3 team,

First of all, many thanks for creating this awesome tool -- recently I've been using it to retrieve RNA-Seq data from various studies.
When I analyze the rse data, I was looking specifically at the sra attributes for Bulk RNA-Seq data. Some of them are not very illustrative, for example: **sra.run_alias**.  For each GSM sample there are replicates, **GSM3167332_r1, GSM3167332_r2, GSM3167332_r3, GSM3167332_r4** 
I am wondering what the "r" specifies? Are they experimental replicates? 

It would be very helpful if you can elaborate on this or you could provide a more detailed descriptions on the columns in the ColData slot in the RSE object. (some of them are not very intuitive to understand)

Many thanks and I am looking forward to your response!

**Comment by lcolladotor** [comment]
Hi @PinaColadast,

Thank you for using `recount3`.

Sadly, we can't help you much. This has to do with the source of the data. Since the Sequence Read Archive (SRA) doesn't have standardized sample metadata variables, each study can be very different from another one. So the `r` portion can mean different things.

I see that that sample at https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3167332 which is on SRA as https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRX4143132&o=acc_s%3Aa and is part of the following SRA study https://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP149374 that has the following runs https://trace.ncbi.nlm.nih.gov/Traces/study/?acc=SRP149374&o=acc_s%3Aa. If I search for the corresponding SRX number there I see https://trace.ncbi.nlm.nih.gov/Traces/study/?acc=SRP149374&search=SRX4143132&o=acc_s%3Aa where the same GSM shows up 6 times. Every single phenotype variable is identical for these six samples. Maybe the associated paper(s) for this SRA study describe more details. But well, that's beyond what we have access to when building a resource like `recount3`.

Best,
Leo
