### ISSUE TITLE
Consider releasing the transcript counts

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/recount3#18]
During our meeting with @ChristopherWilks and @Nick-Eagles, I brought up that we might want to release the Salmon transcript files. This could benefit projects like http://research.libd.org/qsvaR/ by @joshstolz that need as input a `RangedSummarizedExperiment` object with transcript counts. 

This would be something we would need to discuss with Ben and Kasper. 

PS This might fit better at https://github.com/langmead-lab/recount-unify though it would also involve updates to the R package.

**Comment by lcolladotor** [comment]
I know that it would only be for 1 annotation, but well, it might still be useful.

**Comment by davemcg** [comment]
Yeah I'm going to second this request - I actually thought the transcript level info was available as part of the pipeline. I just had an tx-level ask about a project I ran with recount3....I suppose I can just look at the pileup to infer if a certain transcript is more used? Or is there a better workaround?

**Comment by ChristopherWilks** [comment]
@davemcg you might be able to use https://bioconductor.org/packages/release/bioc/html/megadepth.html along with the recount3 BigWigs to do something like pileup of base sums against the transcript exon extents. But I haven't done it myself so I can't comment on how well that'd work.  

As far as making the Salmon results publicly available there's two technical issues with that (I can't address what the policy would be since I'm not making that decision and I'm no longer at Hopkins):

1) they'd need to be moved from backup storage to the recount3 filesystem (relatively easy, but could take some time)

2) they're per sample, so unless someone else at Hopkins is willing to spend the time to aggregate them, it'd be a similar situation to the BigWigs, each sample would have its own Salmon results and the burden would be on the user to aggregate them for a study

**Comment by lcolladotor** [comment]
Hi!

Thanks for the comments Chris =) I do think that both are feasible, it's just whether we would want to actually upload them. I would need to talk to Ben and Kasper about this. I forget now what were other potential downsides; it's been a while since we discussed them ^^'

**Comment by lcolladotor** [comment]
I believe that we have decided against releasing the transcript counts in the end.
