### ISSUE TITLE
Data including metadata and annotation data unavailable for human projects

### ISSUE THREAD

**Issue by lonsbio** [LieberInstitute/recount3#19]
Several  data URLs for recount3 seem unavailable 

## Context

Trying to use `recount3` I am getting intermittent data errors with `404 Not Found` errors. 
 
## Code

Following the example code in the documentation:

```R
available_projects()
```
Result: 
```
Error in file(file, "rt") : invalid 'description' argument
In addition: Warning messages:
1: The 'url' <http://duffel.rail.bio/recount3/human/data_sources/sra/metadata/sra.recount_project.MD.gz> does not exist or is not available. 
2: The 'url' <http://duffel.rail.bio/recount3/human/data_sources/gtex/metadata/gtex.recount_project.MD.gz> does not exist or is not available. 
3: The 'url' <http://duffel.rail.bio/recount3/human/data_sources/tcga/metadata/tcga.recount_project.MD.gz> does not exist or is not available. 
4: The 'url' <http://duffel.rail.bio/recount3/human/collections/recount_brain/metadata/recount_brain.recount_project.MD.gz> does not exist or is not available. 
```

Additionally, to rule out an `R` error I have tried accessing raw files from multiple network locations, i.e using https://rna.recount.bio/docs/raw-files.html#raw-files as a reference, I can't download the following:

[http://duffel.rail.bio/recount3/human/annotations/gene_sums/human.gene_sums.G026.gtf.gz](http://duffel.rail.bio/recount3/human/annotations/gene_sums/human.gene_sums.G026.gtf.gz)

fails. 

The only one that seems to work is: 

[http://duffel.rail.bio/recount3/mouse/annotations/exon_sums/mouse.exon_sums.M023.gtf.gz](http://duffel.rail.bio/recount3/mouse/annotations/exon_sums/mouse.exon_sums.M023.gtf.gz)

**Comment by lcolladotor** [comment]
Hi,

The "intermittent" errors might be either to (a) an R session that you used prior to _Tue, Mar 1, 2022 at 12:47 PM_ US Eastern or (b) where you loaded `recount3` prior to _Tue, Mar 1, 2022 at 12:47 PM_ US Eastern, used `project_homes()` once, left open, and then tried using again later.

Case (b) would be due to the results getting cached https://github.com/LieberInstitute/recount3/blob/master/R/project_homes.R#L48-L52 and then re-used at https://github.com/LieberInstitute/recount3/blob/master/R/project_homes.R#L37-L38 during a given R session. This internal cache makes it easier to re-run `project_homes()` many times during an R session without having to read the `homes_index` file every time.

In any case, @ChristopherWilks @Nick-Eagles and I made a change during a meeting yesterday that was reported by Timothy Shaw (via email, that's why you can't see it here T_T) and that we fixed earlier today. Timothy already reported that the update we did works.

The overall context is that we are planning on adding the `recount_brain` collection to `recount3` and were talking about what files were needed, etc. We forgot that it would break the R package, sorry!

Thank you a lot for reporting this @lonsbio and for using `recount3` =) I'll paste here my email earlier answer to Timothy.

Best,
Leo

```
Hi Tim,

Please post questions like this at https://github.com/LieberInstitute/recount3/issues such that others can benefit from the answers.

Chris, Nick and I were discussing some updates yesterday and we edited the file `/datascope/recount3/release/human/homes_index`. Chris, I realized that I don't have write access to that file:

$ ls -lh homes_index
-rw-r--r-- 1 cwilks3 recount 79 Feb 28 15:17 homes_index

Can you give the recount group write permissions? I know that will take a while. To solve Tim's problem we can simply revert the homes_index until Nick is ready to add recount_brain. 


Tim, you could also do the following thanks to https://github.com/LieberInstitute/recount3/blob/master/R/project_homes.R#L37-L38:

options("recount3_organism_human_project_homes_URL_http://duffel.rail.bio/recount3" = c("data_sources/sra", "data_sources/gtex", "data_sources/tcga"))


See how it works below:

> options("recount3_organism_human_project_homes_URL_http://duffel.rail.bio/recount3" = c("random/random2"))
> project_homes()
[1] "random/random2"

Best,
Leo
```

**Comment by lonsbio** [comment]
Thanks @lcolladotor for your prompt response! 

I think that clears things up a little bit; `recount_brain` was indeed the first file I noticed that was missing, and caused `available_projects()` to error. 

After applying the fix:

```R
options("recount3_organism_human_project_homes_URL_http://duffel.rail.bio/recount3" = c("data_sources/sra", "data_sources/gtex", "data_sources/tcga"))
```

it is no longer missing. However I still have access issues with the main projects: 

```
> available_projects()
Error in file(file, "rt") : invalid 'description' argument
In addition: Warning messages:
1: The 'url' <http://duffel.rail.bio/recount3/human/data_sources/sra/metadata/sra.recount_project.MD.gz> does not exist or is not available. 
2: The 'url' <http://duffel.rail.bio/recount3/human/data_sources/gtex/metadata/gtex.recount_project.MD.gz> does not exist or is not available. 
3: The 'url' <http://duffel.rail.bio/recount3/human/data_sources/tcga/metadata/tcga.recount_project.MD.gz> does not exist or is not available. 
```

I've tried deleting the cache folder as well, and reinstalling `recount3`

From a seperate machine, I can't download one of those files directly either, e.g.: 

```bash
wget http://duffel.rail.bio/recount3/human/data_sources/sra/metadata/sra.recount_project.MD.gz
```

I think my impression of intermittent came about because `recount_brain` couldn't be found and then all 4, but perhaps they are two distinct issues?

**Comment by lcolladotor** [comment]
Hi,

Indeed, I think that they are two separate issues. I can reproduce the 404 error with `wget http://duffel.rail.bio/recount3/human/data_sources/sra/metadata/sra.recount_project.MD.gz`.

I've pinged @ChristopherWilks to help me check whether (a) it's an issue with the data host and their data servers (IDIES: https://idies.jhu.edu/) or (b) due to my request to Chris for giving me and @Nick-Eagles write access to files at IDIES. From what I can see, I suspect that it's (a) but I'm not sure.

Best,
Leo

**Comment by lcolladotor** [comment]
Ahh, but part of the tree doesn't have execute permissions for "others":

```bash
$ ls -lh /datascope/recount3/release | grep human
drwxrwxr-- 6 cwilks3 recount   7 Mar  1 12:44 human
```

Could that be the source of the problem then @ChristopherWilks? Would then `chmod o+x -R /datascope/recount3/release` fix it? The date is also suspicious: today at 12:44 pm US Eastern.

**Comment by lonsbio** [comment]
Can confirm, `available_projects` looking a lot better now from my end: 

```R
> available_projects()
2022-03-02 16:25:50 caching file sra.recount_project.MD.gz.
2022-03-02 16:25:51 caching file gtex.recount_project.MD.gz.
2022-03-02 16:25:53 caching file tcga.recount_project.MD.gz.
      project organism file_source     project_home project_type n_samples
1   SRP107565    human         sra data_sources/sra data_sources       216
2   SRP149665    human         sra data_sources/sra data_sources         4
3   SRP017465    human         sra data_sources/sra data_sources        23
4   SRP119165    human         sra data_sources/sra data_sources         6
5   SRP133965    human         sra data_sources/sra data_sources        12
6   SRP096765    human         sra data_sources/sra data_sources         7
7   SRP124965    human         sra data_sources/sra data_sources        12
8   SRP189165    human         sra data_sources/sra data_sources        15
9   SRP050365    human         sra data_sources/sra data_sources        10
...
```

Thanks @ChristopherWilks  @lcolladotor for resolving this so quickly!

**Comment by lcolladotor** [comment]
Thanks Chris!! And thanks again @lonsbio for reporting this issue before it got larger =)

**Comment by toddajohnson** [comment]
I have been trying to access recount3 TCGA BigWig files through either the recount3 study explorer or from the recount3 Bioconductor package (ver.1.40), but both were unable to access the URLs.
For instance: rtracklayer::import.bw('http://duffel.rail.bio/recount3/human/data_sources/tcga/base_sums/RC/KIRC/01/tcga.base_sums.KIRC_a45f3a18-fe01-4651-8421-bec9219d9201.ALL.bw')
results in:
Error in seqinfo(ranges) : UCSC library operation failed
In addition: Warning message:
In seqinfo(ranges) :
  Couldn't open http://duffel.rail.bio/recount3/human/data_sources/tcga/base_sums/RC/KIRC/01/tcga.base_sums.KIRC_a45f3a18-fe01-4651-8421-bec9219d9201.ALL.bw

I just tried the study explorer filtering on human:tcga:KIRC and tried using one of the BigWig URLs from the csv file in UCSC Genome Browser, but "Warning: Couldn't open..."

Is this related to the above problem?

**Comment by ChristopherWilks** [comment]
hi @toddajohnson, yes this was related, thanks for bringing it to our attention, the misguided permissions change affected more than I initially thought.  BigWigs and Junctions (both partially affected) should now be fixed.  Please let us known if you run into any more issues.

**Comment by toddajohnson** [comment]
Hi @ChristopherWilks, I tried one of the BigWig URLs and it now loads correctly in UCSC Genome Browser, but FYI, as this may be unrelated to the current issue, in the recount3 study explorer the link to "BigWig UCSC track hub" fails.  For instance the link and/or just manually adding https://raw.githubusercontent.com/LieberInstitute/recount3-docs/master/UCSC_hubs/human/data_sources_KIRC/hub.txt as a custom track to UCSC fails with a 404 error.

**Comment by ChristopherWilks** [comment]
ok, thanks, good to know the BigWigs are working.
I'll defer to @lcolladotor as he set the hubs up, however, I'm not sure of that URL, but this one works:
https://raw.githubusercontent.com/LieberInstitute/recount3-docs/master/UCSC_hubs/human/tcga_KIRC/hub.txt

**Comment by lcolladotor** [comment]
The link @toddajohnson provided used `data_sources_KIRC` instead of `tcga_KIRC`.  This is unrelated to the initial issue, so in the future please make a new issue. In any case, thanks for reporting it.

It's been fixed at https://github.com/LieberInstitute/recount3-docs/commit/b4b8684f19f1f659618845805998a597393c2d18.

See https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr1&hubUrl=https://raw.githubusercontent.com/LieberInstitute/recount3-docs/master/UCSC_hubs/human/tcga_KIRC/hub.txt for example.
