### ISSUE TITLE
Error: 'recount3_url' is not a valid supported URL when I run "human_projects <- available_projects()"                                                                                  

### ISSUE THREAD

**Issue by bitmman** [LieberInstitute/recount3#31]
## Describe the bug

After loading recount3 R package, when I run human_projects <- available_projects(), it reports "Error: 'recount3_url' is not a valid supported URL since it's missing the URL/<organism>/homes_index text file or 'recount3_url' is not an existing directory in your file system.". This function runs properly a while ago. But It's not working on both my desktop and laptop, so I'm guessing it's not the problem of my file system because I haven't modify anything both on my desktop and laptop.

### Provide a minimally reproducible example (reprex)

library("recount3")
human_projects <- available_projects()

**Comment by priyambial123** [comment]
I get the same error message. How did you resolve this issue?

Thank you

**Comment by lcolladotor** [comment]
Hi again,

If you are a Windows user, `duffel` now fully works on that operating system. That is, the duffel access issue has now been addressed by the internal switch from `RCurl::url.exists()` to `httr::http_error()`. You can gain access to these updates by installing `recount3` version 1.10.2 (bioc-release aka 3.17) or 1.11.2 (bioc-devel aka 3.18).

duffel currently points to https://registry.opendata.aws/recount/ instead of IDIES.

Best,
Leo
