### ISSUE TITLE
Combining multiple RSE

### ISSUE THREAD

**Issue by harish0201** [LieberInstitute/recount3#8]
Hi!

I was looking forward to analyze a few datasets from Cancer and I stumbled upon recount3! I love that I can grab all the resource from here itself.

Since some of the data that I'm planning to work upon are available on TCGA and some on GTEx, I was wondering if there was a way to combine the two project infos to build the RSE. Is this possible currently? Or would you consider making this an option?

For examples:

```
project<- subset(human_projects, project ==c("BRCA","PCPG") & project_type== "data_sources")
news <- create_rse(project)
```

But then this shows an error saying: 
```
Error in create_rse(project) : 'project_info' should only have one row
```

**Comment by lcolladotor** [comment]
Hi,

_RangedSummarizedExperiment_ objects can be combined *if* they have the same features (genes typically, aka `rowData(rse)`) and sample variables (aka `colnames(colData(rse))`). You can do so for many studies.

However, since you are talking about 2 RSEs from different data sources (GTEx and TCGA) which have different data source-specific variables,  you'll either have to harmonize them (like we did in the `recount-brain` project (https://www.biorxiv.org/content/10.1101/618025v1) for a set of samples) or drop them before using `cbind()`. 

Since this decision becomes really study specific, we don't have code for this. `recount3` does support *collections* of studies, which comes down to a text table with the harmonized sample variables. If you make one for the studies you are working on, we could potentially add it to the resource and make it easier for future users to use the same samples you used. 

Best,
Leo

**Comment by harish0201** [comment]
Awesome! Thank you for the help and resources pointing in the right way.

Can I close this issue, and drop a few comments if any in case I face any issues or require clarification?
